// Snapshot the team's public Nostr profiles for the /about/ page.
//
//   npm run fetch:profiles
//
// For every name in .well-known/nostr.json this reads the newest kind 0
// event, writes _data/profiles.yml (name, a shortened `about`, npub, the
// picture's local path) and saves the picture under assets/images/people/,
// resized by tools/profiles/resize.py when python3 with Pillow is around.
//
// The page never fetches anything itself: the site's CSP allows no
// third-party images, and a profile edit should not change the site until
// someone re-runs this and commits the result. A person's entry in
// _data/pages/about.yml may override any field with a value of its own.

import { SimplePool, useWebSocketImplementation } from 'nostr-tools/pool'
import { npubEncode } from 'nostr-tools/nip19'
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { dirname, resolve, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

useWebSocketImplementation(globalThis.WebSocket)
// Node's WebSocket re-fires `error` on close; nostr-tools then recurses. Not
// a browser problem, and not what this script is about.
process.on('uncaughtException', () => {})

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const RELAYS = ['wss://purplepag.es', 'wss://relay.nostr.band', 'wss://relay.damus.io', 'wss://nos.lol']
const RAW = resolve(root, 'tools/profiles/raw')
const OUT = resolve(root, 'assets/images/people')
const ABOUT_MAX = 160

const names = JSON.parse(readFileSync(resolve(root, '.well-known/nostr.json'), 'utf8')).names
mkdirSync(RAW, { recursive: true })
mkdirSync(OUT, { recursive: true })

/**
 * First sentence or two of a profile's `about`: lines that are links or
 * emoji-led list items are dropped first, then sentences are taken until the
 * budget is spent. No `<` or `>` survives, so check.sh stays happy.
 */
function shorten(about = '') {
  const kept = about
    .split(/\r?\n/)
    .map((l) => l.replace(/https?:\/\/\S+/g, '').replace(/#(\w)/g, '$1').replace(/[<>]/g, '').trim())
    .filter((l) => /^[\p{L}\p{N}"'(]/u.test(l))
  const text = kept.join(' ').replace(/\s+/g, ' ').trim()
  const out = []
  for (const sentence of text.match(/[^.!?]+[.!?]+(?=\s|$)|[^.!?]+$/g) || []) {
    const next = (out.join(' ') + ' ' + sentence.trim()).trim()
    if (out.length && next.length > ABOUT_MAX) break
    out.push(sentence.trim())
  }
  return out.join(' ').slice(0, ABOUT_MAX + 40)
}

/** YAML double-quoted scalar; no `<` survives shorten(), so check.sh stays happy. */
const q = (s) => JSON.stringify(String(s ?? ''))

const pool = new SimplePool()
const lines = ['# Generated by `npm run fetch:profiles` — do not edit. Override per person in _data/pages/about.yml.', '']
let failures = 0

for (const [name, pubkey] of Object.entries(names)) {
  const ev = await pool.get(RELAYS, { kinds: [0], authors: [pubkey] }, { maxWait: 8000 }).catch(() => null)
  let p = {}
  try {
    p = JSON.parse(ev?.content || '{}')
  } catch {}
  const npub = npubEncode(pubkey)
  const display = p.display_name || p.name || name
  let picture = ''
  if (p.picture && /^https:\/\//.test(p.picture)) {
    try {
      const res = await fetch(p.picture, { signal: AbortSignal.timeout(15000) })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const type = res.headers.get('content-type') || ''
      const ext = type.includes('png') ? '.png' : type.includes('webp') ? '.webp' : type.includes('gif') ? '.gif' : '.jpg'
      const raw = resolve(RAW, name + ext)
      writeFileSync(raw, Buffer.from(await res.arrayBuffer()))
      const out = resolve(OUT, name + '.jpg')
      const py = spawnSync('python3', [resolve(root, 'tools/profiles/resize.py'), raw, out], { encoding: 'utf8' })
      if (py.status === 0) {
        picture = `/assets/images/people/${name}.jpg`
      } else {
        // No Pillow: ship the original under its own extension.
        const fallback = resolve(OUT, name + extname(raw))
        copyFileSync(raw, fallback)
        picture = `/assets/images/people/${name}${extname(raw)}`
        console.warn(`  ${name}: resize skipped (${(py.stderr || py.error?.message || '').trim() || 'python3 unavailable'})`)
      }
    } catch (err) {
      console.warn(`  ${name}: picture not fetched (${err.message})`)
      if (existsSync(resolve(OUT, name + '.jpg'))) picture = `/assets/images/people/${name}.jpg`
    }
  }
  if (!ev) {
    failures++
    console.warn(`  ${name}: no kind 0 found on ${RELAYS.length} relays`)
  }
  lines.push(
    `${name}:`,
    `  name: ${q(display)}`,
    `  about: ${q(shorten(p.about))}`,
    `  npub: ${npub}`,
    `  nip05: ${q(p.nip05 || '')}`,
    `  picture: ${q(picture)}`,
    `  fetched: ${new Date().toISOString().slice(0, 10)}`,
    '',
  )
  console.log(`${name}: ${display}${picture ? '  [picture]' : ''}`)
}

writeFileSync(resolve(root, '_data/profiles.yml'), lines.join('\n'))
console.log(`wrote _data/profiles.yml${failures ? ` (${failures} profile(s) missing)` : ''}`)
pool.destroy()
process.exit(0)
